### PR TITLE
Add loadout information

### LINKED ISSUE #21: Player loadout
- [ ] Parse item equip/unequip events
- [ ] Determine UI/UX for rendering
- [ ] Implement rendering

### PR DESCRIPTION
**Pull request by patrickgordon**
This PR is a WIP.

- [x] Parse item equip/unequip events
- [x] Parse item attach / unattach events
- [x] Implement UI 

Resolves #21

### CODE REVIEW

**Comment by patrickgordon** [comment]
hey @apazzolini I think I'm done. I'm concerned that I have introduced some performance problems though and I can't quite narrow down if I have and possibly where.

Could you please take a look?

**Comment by apazzolini** [comment]
Awesome! Yes, I will take a look at this tonight.

**Comment by apazzolini** [comment]
Really awesome work on this @patrickgordon! The code looks great, and the tooltip is really helpful. Cool to see items change as people loot.

Performance is still looking OK for me. Are you testing on the production build? styled-components is very slow in dev.

```
yarn global add serve
yarn run build
serve -s build
```

Visit the URL serve gives you and run this (I have it saved as a bookmarklet):

```
javascript:(function(){var script=document.createElement('script');script.onload=function(){var stats=new Stats();document.body.appendChild(stats.dom);requestAnimationFrame(function loop(){stats.update();requestAnimationFrame(loop)});};script.src='//rawgit.com/mrdoob/stats.js/master/build/stats.min.js';document.head.appendChild(script);})()
```

It should be a (near) constant 60 FPS, or faster if you have a monitor with a higher refresh rate. I get a couple of small drops to low 50s, but I profiled the app with Chrome's devtools and I don't see anything related to the stuff you've worked on there causing a problem.

I do have a few other notes before merging this in though:

1. Hovering over the first person with a lot of items causes it to clip the browser. We need to detect that and adjust the tooltip down to ensure it's always visible: https://cl.ly/4d040f5fab1c

2. The itemId.json update causes a regression on some item names that I changed myself (for example, `Item_Attach_Weapon_Muzzle_Suppressor_Large_C` should be `AR/DMR Supressor` instead of `Large Supressor`). I think instead of having these files in the repo, we should use a git submodule and regex replace small, medium, and large with SMG, AR/DMR, and SR.

3. Was there a specific reason to implement `Tooltip` by hand instead of using https://github.com/tvkhoa/react-tippy? I'm totally OK with it if there was, just curious. I'm all in favor of lighter weight options. Also, if we do want to go with our own wrapper, can we use the new [forwardRef API](https://reactjs.org/docs/forwarding-refs.html)? We'll likely need to grab the ref to solve #1. 

Let me know if you want me to tackle any of these, I don't want to throw extra work your way if you don't want to do it - I really appreciate everything you've done already, seriously great stuff.

**Comment by patrickgordon** [comment]
OK yep I noticed but forgot to fix the clipping issue. I will look in to that one. I will also fix the regression in the item names. Agree that using a git repo of some sort would be useful to ensure that these regressions are avoided in future. I'm gonna leave that for later implementation though as I think it might interfere with the scope of this PR.

The reason for opting to not go with react-tippy is because it is [not being very actively maintained](https://github.com/tvkhoa/react-tippy/issues/84). The author of tippyjs has provided the wrapper from which that one was "inspired" from. The forwardRef API is news to me -- looks very promising actually and super convenient!

**Comment by apazzolini** [comment]
Cool, sounds good on all of those points. For the Beryl icon, see here: https://media.discordapp.net/attachments/418527835385233419/487102558029086730/beryl762_icon.png?width=400&height=130

I think the QBU icon is missing too - we'll need to extract it from the game assets manually. The above icon was extract by Webdestroya, he pointed to these two files:

```
/TslGame/Content/UI/Weapon/weapons_gun_M762.uasset
/TslGame/Content/UI/item/weapon/icon_weapon_M762.uasset
```

I assume the QBU icons will be somewhere nearby.

**Comment by patrickgordon** [comment]
Roger that will add those too

**Comment by apazzolini** [comment]
So there was another gun released this week... :)

Aside from that, everything else looks really nice. Good find on the popper option. I have a few small UI things I want to try out, but overall I think we're super close. If you can grab that new gun icon, I'll do a couple of small CSS tweaks and then I think that's it! Should be able to merge this in the next couple of days

**Comment by patrickgordon** [comment]
OK I will add the new gun :+1:

**Comment by patrickgordon** [comment]
Done @apazzolini.

**Comment by apazzolini** [comment]
@patrickgordon I've merged these changes into develop after tweaking a few things:

- A couple of minor lint fixes
- CSS tweaks
- Changed equipment list to always show the 4 categories with placeholder icons and override them once equipment exists in that category
- Ensure sort order of weapons (Main, Handgun, Melee) and alphabetical sorting of Main weapons so they don't jump around

Take a look and tell me what you think. If you feel it's looks good, I'll merge to master :)

**Comment by patrickgordon** [comment]
looks good to me @apazzolini ! thanks for the extra effort.

**Pull request merged**
